### ISSUE TITLE
Deletion does not work

### ISSUE THREAD

**Issue by Natanji** [mgutekunst/WP8-PwdHash#1]
Hi,
I just stumbled upon this nice little app, but was a bit surprised that the deletion doesn't seem to work at all. This is not surprising when looking at the code, since the deleteItems() function merely removes the items from the list, but does not commit the change to storage. The deleteHash function should probably be called there instead, right now it is not even used. This results in all hashes that were deleted re-appearing once you re-open the app.

As a work-around I can delete all items, then add a new dummy entry; this will trigger committing the change in the displayed list to storage.

Since the app is the only PwdHash app in the Windows store, it would be great if you could fix this quickly and submit that change to Microsoft. ;)

**Comment by mgutekunst** [comment]
Hi, 
thanks for reporting this. I'll take a look in the next couple of days, I think.

**Comment by mgutekunst** [comment]
Should be fixed in the new release for Windows phone

**Comment by Natanji** [comment]
I haven't seen any update yet, did you upload it to the Windows Store? (I am using Windows 10, not Windows phone) @mgutekunst

**Comment by mgutekunst** [comment]
Oh, sorry @Natanji . 
I never thought anyone would use the Windows 8.1 variant of this app. So I just uploaded the Windows phone version until today. 

That said, you should get an update in the next couple of days. Sorry for the trouble.
